# Generated by Django 3.1.5 on 2021-06-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmitglied',
            name='kenntnis_ordn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalmitglied',
            name='stammdatenblatt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalmitglied',
            name='verpfl_datengeheimnis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalmitglied',
            name='wahl_angenommen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mitglied',
            name='kenntnis_ordn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mitglied',
            name='stammdatenblatt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mitglied',
            name='verpfl_datengeheimnis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mitglied',
            name='wahl_angenommen',
            field=models.BooleanField(default=False),
        ),
    ]
