# Generated by Django 3.1.5 on 2021-06-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0002_auto_20210615_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmitglied',
            name='tel_weitergabe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mitglied',
            name='tel_weitergabe',
            field=models.BooleanField(default=False),
        ),
    ]
