// --- 1. Projektthema -------------------------
= Anwenderdokumentation: {project-name}
// --- 2. Teammitglieder -----------------------
Paul Wentzel <s83970@htw-dresden.de>; Georg Schicker <s83938@htw-dresden.de>; Nathalie Kästner <s83816@htw-dresden.de>; Collin Neumann <s84599@htw-dresden.de>; Lennart Bronke <s83778@htw-dresden.de>
// --- 3. Abgabedatum --------------------------
26. Juni 2023
// ---------------------------------------------
:docs: ../../docs
include::{docs}/_includes/default-attributes.inc.adoc[]
// ---
:doctype: book
:toc:
:toclevels: 2
:toc-title: Inhaltsverzeichnis
:sectnums:
:icons: font
//:source-highlighter: highlightjs
:source-highlighter: rouge
:rouge-style: github
:xrefstyle: full
:experimental:
:chapter-signifier:
:figure-caption: Abbildung
:table-caption: Tabelle
:listing-caption: Listing
:!example-caption:
:experimental:
// Folders
:imagesdir-reset: {imagesdir}
:docs-test2: {docs}/test2
:docs-requirements: {docs}/requirements
:docs-project-management: {docs}/project_management
:docs-architecture: {docs}/architecture
:docs-test: {docs}/test
:docs-development: {docs}/development

<<<

// --- 4. include Pfade anpassen ---------------

:imagesdir: {docs-requirements}/images

== Einführung

=== Zweck

Die vorliegende Web-Anwendung dient der Verwaltung der Mitglieder des Studentenrates der HTW Dresden. Diese ermöglicht es, Mitglieder übersichtlich zu listen und zu bearbeiten, neue Mitglieder einfach anzulegen und über entsprechende Berechtigungen der Mitglieder zu informieren. +
Ziel der Anwendung ist es, die bisherige unübersichtliche Organisation über Excel-Tabellen zu ersetzen und die Verwaltung der Mitglieder zeiteffizienter und intuitiver zu gestalten.

=== Funktionsumfang

Während unserer Projektarbeit haben wir ein bereits vorhandenes System weiterentwickelt. Hierbei wurden neue Funktionen einerseits ergänzt und bereits vorhandene Funktionen erweitert beziehungsweise je nach Bedarf auch entfernt. +
So wurde die von unseren Vorgängern zuvor implementierte Verwaltung von Kandidaturen nun wieder entfernt, da diese vom Auftraggeber nicht mehr gewünscht wurde. +
Des Weiteren wird nun bei der Neuanlage oder Bearbeitung eines Mitglieds automatisch eine Checkliste erstellt, welche Berechtigung diesem entsprechend seines Amtes noch zu vergeben sind (Schlüssel, Websitegruppen etc.).

== Aufbau der Benuzeroberfläche am Beispiel des Tabs "Mitglieder"

== Nutzung als Admin

=== Vorbedingungen

=== Usw...

== Nutzung als User

=== Vorbedingungen

=== Usw...

== Allgemeine Hinweise

== Weiterführende Dokumentation
