// --- 1. Projektthema -------------------------
= Testdokumentation: {project-name}
// --- 2. Teammitglieder -----------------------
Paul Wentzel <s83970@htw-dresden.de>; Georg Schicker <s83938@htw-dresden.de>; Nathalie Kästner <s83816@htw-dresden.de>; Collin Neumann <s84599@htw-dresden.de>; Lennart Bronke <s83778@htw-dresden.de>
// --- 3. Abgabedatum --------------------------
26. Juni 2023
// ---------------------------------------------
:docs: ../../docs
include::{docs}/_includes/default-attributes.inc.adoc[]
// ---
:doctype: book
:toc:
:toclevels: 2
:toc-title: Inhaltsverzeichnis
:sectnums:
:icons: font
//:source-highlighter: highlightjs
:source-highlighter: rouge
:rouge-style: github
:xrefstyle: full
:experimental:
:chapter-signifier:
:figure-caption: Abbildung
:table-caption: Tabelle
:listing-caption: Listing
:!example-caption:
:experimental:
// Folders
:imagesdir-reset: {imagesdir}
:docs-test2: {docs}/test2
:docs-requirements: {docs}/requirements
:docs-project-management: {docs}/project_management
:docs-architecture: {docs}/architecture
:docs-test: {docs}/test
:docs-development: {docs}/development

<<<

// --- 4. include Pfade anpassen ---------------

== Testkonzept

Diese Testdokumentation konzentriert sich auf die Überprüfung der Funktionalitäten und Usability der Website, die wir im Rahmen des Projekts übernommen und weiterentwickelt haben. Unsere Tests ergänzen die bereits durchgeführten Unit- und Integrationstests unserer Vorgänger.

*Folgende Testmethoden/-verfahren wurden eingesetzt:*

* Funktionstests (automatisiert)
** Einzelne Funktionen der Website wurden mit praxisnahen Beispieldatensätzen überprüft, um sicherzustellen, dass das Ergebnis den Anforderungen bzw. Erwartungen des Stakeholders entspricht
* Akzeptanztest
** Im Rahmen eines Akzeptanztests überprüften die Stakeholder, ob das Projekt Ihre Erwartungen erfüllt

Unser Hauptziel war eine einwandfrei funktionierende Website, die den funktionalen Anforderungen entspricht und eine optimale Benutzererfahrung bietet.

Bei den Funktionstests entschieden wir uns für eine automatisierte Methode, um menschliche Fehler wie zum Beispiel fehlerhafte Benutzereingaben zu vermeiden. Zudem würde der Zeitaufwand von manuellen Tests die Implementierung eines automatisieren Tests übersteigen, da wir von den Stakeholdern eine größere Menge an Beispieldaten zur Verfügung gestellt bekommen haben.

== Testdokumentation

*Testfallbeschreibung*

Die Testfälle werden tabellerisch sowie 

== Ergebnisse der Testdurchführung

=== Test Case zu Use Case 07 - Checkliste erstellen

==== Allgemeine Informationen


==== Checkliste anlegen

==== ...

=== ...

=== Akzeptanztests

==== Allgemeine Aufgaben

==== Ablauf

==== Funktionstests

==== Hinweise/Wünsche