// --- 1. Projektthema -------------------------
= Testdokumentation: {project-name}
// --- 2. Teammitglieder -----------------------
Paul Wentzel <s83970@htw-dresden.de>; Georg Schicker <s83938@htw-dresden.de>; Nathalie Kästner <s83816@htw-dresden.de>; Collin Neumann <s84599@htw-dresden.de>; Lennart Bronke <s83778@htw-dresden.de>
// --- 3. Abgabedatum --------------------------
26. Juni 2023
// ---------------------------------------------
:docs: ../../docs
include::{docs}/_includes/default-attributes.inc.adoc[]
// ---
:doctype: book
:toc:
:toclevels: 2
:toc-title: Inhaltsverzeichnis
:sectnums:
:icons: font
//:source-highlighter: highlightjs
:source-highlighter: rouge
:rouge-style: github
:xrefstyle: full
:experimental:
:chapter-signifier:
:figure-caption: Abbildung
:table-caption: Tabelle
:listing-caption: Listing
:!example-caption:
:experimental:
// Folders
:imagesdir-reset: {imagesdir}
:docs-test2: {docs}/test2
:docs-requirements: {docs}/requirements
:docs-project-management: {docs}/project_management
:docs-architecture: {docs}/architecture
:docs-test: {docs}/test
:docs-development: {docs}/development

<<<

// --- 4. include Pfade anpassen ---------------

== Testkonzept

Diese Testdokumentation konzentriert sich auf die Überprüfung der Funktionalitäten und Usability der Website, die wir im Rahmen des Projekts übernommen und weiterentwickelt haben. Unsere Tests ergänzen die bereits durchgeführten Unit- und Integrationstests unserer Vorgänger.

*Folgende Testmethoden/-verfahren wurden eingesetzt:*

* Funktionstests (automatisiert)
** Einzelne Funktionen der Website wurden mit praxisnahen Beispieldatensätzen überprüft, um sicherzustellen, dass das Ergebnis den Anforderungen bzw. Erwartungen des Stakeholders entspricht
* Akzeptanztest
** Im Rahmen eines Akzeptanztests überprüften die Stakeholder, ob das Projekt Ihre Erwartungen erfüllt

Unser Hauptziel war eine einwandfrei funktionierende Website, die den funktionalen Anforderungen entspricht und eine optimale Benutzererfahrung bietet.

Bei den Funktionstests haben wir uns für eine automatisierte Methode entschieden, um menschliche Fehler, wie zum Beispiel fehlerhafte Benutzereingaben, zu vermeiden. Zudem würde der Zeitaufwand von manuellen Tests die Implementierung eines automatisieren Tests übersteigen, da wir die Tests öfter anpassen möchten.

== Testdokumentation

*Testfallbeschreibung*

Die Testfälle werden tabellerisch und gegebenenfalls mithilfe einer detaillierten Logdatei beschrieben. Jeder Testfall wird mit einer Testfallnummer, Vorbedingungen, Eingabedaten, den Schritten zur Durchführung des Tests sowie dem erwarteten Ergebnis dokumentiert.

Da der Tester gleichzeitig auch eine Rolle als Entwickler einnimmt, werden entdeckte Fehler sofort analysiert und behoben. Dies erzeugt zwar einen erhöhten Aufwand für eine Person, verspricht dafür jedoch einen idealen Workflow ohne längere Wartezeiten.

Person, welche getestet hat: Collin Neumann (Test sowie Entwicklung)

== Ergebnisse der Testdurchführung

Unsere Testergebnisse waren im 1. Durchlauf bis auf eine Ausnahme erfolgreich. Der Grund für den Fehlschlag war, dass ein Mitglied einen Umlaut im Nachnamen hatte, der im E-Mail-Feld zu einer Fehlermeldung führte, welcher das Hinzufügen des Mitglieds verhinderte. Wir interpretieren den Fehlschlag jedoch als nicht schwerwiegend, da dieser im Falle eines manuellen Tests nicht passiert wäre (die Fehlermeldung ist für Benutzer eindeutig).

Der zweite Testlauf war durchweg erfolgreich. 

Rückwirkend betrachtet erachten wir die automatisierte Lösung als eine gute Wahl, da diese mittels einer Logdatei eine leichte Dokumentierung ermöglichte.
----
Name:  Paul Wentzel
Position:  Service/Buchhaltung (Angestellte)
Berechtigung1: Zugang: Schleuse
Berechtigung2: Schlüssel4

Test für Paul Wentzel erfolgreich
#############################################
Name:  Georg Schicker
Position:  Mitglied Ausschuss Finanzielles (Ausschüsse des StuRa)
Berechtigung1: Zugang: Schleuse
Berechtigung2: Schlüssel5
Berechtigung3: Schlüssel6

Test für Georg Schicker erfolgreich
#############################################
Name:  Collin Neumann
Position:  Leitung Beauftragung Datenschutz (Beauftragte des StuRa)
Berechtigung1: Zugang: Schleuse
Berechtigung2: Schlüssel8

Test für Collin Neumann erfolgreich
#############################################
Name:  Nathalie Kaestner
Position:  studentische Vertretung (Beitrag Projekt eCampus)
Berechtigung1: Zugang: Schleuse

Test für Nathalie Kaestner erfolgreich
#############################################
Name:  Lennart Bronke
Position:  SprecherIn Sprecherinnen und Sprecher (Fachausschuss Bauingenieurswesen/Architektur)
Berechtigung1: Zugang: Schleuse

Test für Lennart Bronke erfolgreich
#############################################
Name:  Collina Neumannski
Position:  SprecherIn Sprecherinnen und Sprecher (Fachausschuss Design)
Berechtigung1: Zugang: Schleuse

Test für Collina Neumannski erfolgreich
#############################################
Durchgeführte Tests: 6
Erfolgreiche Tests: 6
Fehlgeschlagene Tests: 0
----

=== Test Case zu Use Case 01 und 07 - Mitglied sowie Checkliste erstellen

==== Allgemeine Informationen

Dieser Testcase soll das automatische Anlegen einer Checkliste und dessen Inhalt (Berechtigungen) überprüfen. Dies geschieht in Verbindung mit dem Anlegen eines Mitglieds, da das Erstellen der Checkliste dies vorraussetzt.

==== Mitglied anlegen

*Ziel:* Erfolgreiche Erstellung eines neuen Mitglieds

*Beschreibung:* Der Anwender möchte ein neues Mitglied in die Datenbank aufnehmen

*Vorbedingungen*:

* Position ist noch nicht vollständig belegt

==== Checkliste überprüfen

*Ziel:* Überprüfung ob die Checkliste beim Anlegen des Mitglieds automatisch erstellt wurde

*Beschreibung:* Der Anwender möchte überprüfen ob für das erstellte Mitglied automatisch eine Checkliste mit passendem Inhalt (Berechtigungen) erzeugt wurde.

*Vorbedingungen*:

* Mitglied war noch nicht vorhanden
* 'Checkliste erstellen' wurde 

==== Berechtigungen überprüfen

=== Akzeptanztests
Protokoll vom XX.06.2023 Schriftführer: Georg Schicker

==== Allgemeine Aufgaben

==== Ablauf

==== Funktionstests

==== Hinweise/Wünsche