= System-Wide Requirements: {project-name}
Vorname Nachname <email@domain.org>; Vorname2 Nachname2 <email2@domain.org>; Vorname3 Nachname3 <email3@domain.org>
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]
// Platzhalter für weitere Dokumenten-Attribute


== Einführung
In diesem Dokument werden die systemweiten Anforderungen für das Projekt Mitgliederdatenbank spezifiziert. Die Gliederung erfolgt nach der FURPS+ Anforderungsklassifikation:

* Systemweite funktionale Anforderungen (F),
* Qualitätsanforderungen für Benutzbarkeit, Zuverlässigkeit, Effizienz und Wartbarkeit (URPS) sowie
* zusätzliche Anforderungen (+) für technische, rechtliche, organisatorische Randbedingungen

NOTE: Die funktionalen Anforderungen, die sich aus der Interaktion von Nutzern mit dem System ergeben, sind als Use Cases in einem separaten Dokument festgehalten. [hier ggf. Verweis einfügen]


== Systemweite funktionale Anforderungen
//Angabe von system-weiten funktionalen Anforderungen, die nicht als Use Cases ausgedrückt werden können. Beispiele sind Drucken, Berichte, Authentifizierung, Änderungsverfolgung (Auditing), zeitgesteuerte Aktivitäten (Scheduling), Sicherheit / Maßnahmen zum Datenschutz
* *SWFA-1: Ein Access-Control für das Backend/Verwaltungsoberfläche ist nötig.*
** Zur Überprüfung können mittels unberechtigter oder gar falscher Logins Zugriffe auf unberechtige Daten oder Use Cases versucht werden.

* *SWFA-2: Änderungen am System oder an der Software sollen dokumentiert werden (Auditing) und leicht nachvollziehbar sein.*
** Zur Validierung können mit verschiedenen Test-Nutzern Daten verändert, gelöscht und hinzugefügt werden. Anschließend werden alle getätigten Änderungen mit der Historie abgeglichen.

* *SWFA-3: Das System muss relevante Daten persistent speichern.*
** Zur Sicherstellung kann eine Reihe plötzlicher Systemausfälle simuliert werden. Bei einer anschließenden Überprüfung werden relevante Daten auf Vollständigkeit überprüft.

== Qualitätsanforderungen für das Gesamtsystem 
//Qualitätsanforderungen repräsentieren das "URPS" im FURPS+ zu Klassifikation von Anforderungen

=== Benutzbarkeit (Usability)
//Beschreiben Sie Anforderungen für Eigenschaften wie einfache Bedienung, einfaches Erlernen, Standards für die Benutzerfreundlichkeit, Lokalisierung (landesspezifische Anpassungen von Sprache, Datumsformaten, Währungen usw.)
* *NFAU-1 Lokalisation:* +
Die Stakeholder sitzen ausschließlich in Deutschland, weshalb die Software deutsch lokalisiert sein soll (Sprache, Datumsformat, Währung).

* *NFAU-2 Erlernbarkeit:* +
Es soll sichergestellt sein, dass auch ein ungelernter Nutzer mithilfe einer Anleitung den Umgang mit der Software problemlos und in absehbarer Zeit (max. 1 Tag) erlernen kann. 

* *NFAU-3 Zugangsbeschränkung:* +
Mithilfe einer Rechteverwaltung soll sichergestellt werden, dass nur berechtige Nutzer Schreibrechte haben. Die Berechtigungen sollen vom Administrator festgelegt werden können.

* *NFAU-4 Benutzerfreundlichkeit:* +
Mithilfe von maximal 3 Klicks sollen relevante Informationen für Mitglieder in einem geordneten Format ausgegeben werden können. Die Ausgabe muss vom Benutzer nach mehreren Kriterien filterbar sein.

* *NFAU-5 Eingabehilfe:* +
Das Tool soll zwischen verpflichtenden und optionalen Eingaben unterscheiden (z.B. Eingabe einer alternativen E-Mail-Adresse). Es ist die Aufgabe des Frontends, dem Nutzer diese Unterscheidung zu verdeutlichen.

=== Zuverlässigkeit (Reliability)

* *NFAR-1 Verfügbarkeit:* +
Website sowie Datenbank benötigen keine 99,99% Erreichbarkeit, sollten jedoch so oft wie möglich verfügbar sein.

* *NFAR-2 Eingabevalidierung:* +
Die Benutzereingaben sind auf Sinnhaftigkeit zu überprüfen um Falscheingaben zu vermeiden (z.B. keine Postleitzahl im Namensfeld). Fehlende Pflichtdaten führen zu einer Eingabeaufforderung an den Nutzer und lösen noch keine Änderung an der Datenbank aus.

* *NFAR-3 Dokumentation:* +
Änderungen sollen dokumentiert werden (z.B. Nutzer A löscht Mitglied B am 01.01.2023). Systemausfälle sollen mittels Log-Dateien nachvollziehbar sein. 

* *NFAR-4 Wiederherstellbarkeit:* +
Im Zweifelsfall müssen Backups vom Nutzer einspielbar sein.

=== Effizienz (Performance)
* *NFAP-1 Serialisierung:* +
Auf die Website sollen bis zu 3 Nutzer gleichzeitig zugreifen können. Datenbankabfragen sollten auch bei hoher Mitgliederanzahl innerhalb von 5 Sekunden ausgeführt sein. 

* *NFAP-2 Workflow:* +
Das Anlegen neuer Datensätze soll direkt erfolgen, um reibungslose Arbeitsabläufe zu gewährleisten.

=== Wartbarkeit (Supportability)
// Dieser Bereich beschreibt sämtliche Anforderungen welche die Supportfähigkeit oder Wartbarkeit des zu entwickelnden Systems verbessern, einschließlich Anpassungsfähigkeit und Erweiterbarkeit, Kompatibilität, Skalierbarkeit und Anforderungen bezüglich der System Installation sowie Maß an Support und Wartbarkeit.
* *NFAS-1 Installation:* +
Es soll eine Installationsanleitung beigelegt werden, welche das selbständige (neu-)installieren der Software durch die Nutzer ermöglicht. 

* *NFAS-2 Erweiterbarkeit:* +
Berechtigte Nutzer sollen Tabellen selbständig verwalten (z.B. Anlegen neuer Spalten) können.

//* *NFAS-3 Kompatibilität:* +


== Zusätzliche Anforderungen

=== Einschränkungen (Constraints)
//Angaben ergänzen, nicht relevante Unterpunkte streichen oder auskommentieren
* *ZAC-1 Plattform:* +
Die Website sowie die Datenbank sollen auf einem Server des StuRa laufen. Des Weiteren soll die Website auf allen aktuell gängigen Browsern nutzbar sein.

//Ressourcenbegrenzungen
* *ZAC-2 Ressourcen:* +
Der StuRa stellt einen Docker zur Verfügung auf dem ein beliebiges Linux-Betriebssystem virtualisiert werden kann.

//zu nutzende Komponenten / Bibliotheken / Frameworks
* *ZAC-3 Implementierung:* +
Es soll kein Java verwendet werden. Das System soll unter Linux lauffähig sein.

//Physische Begrenzungen für Hardware, auf der das System betrieben werden soll

=== Organisatorische Randbedingungen
//Angaben ergänzen, nicht relevante Unterpunkte streichen oder auskommentieren
//* Anforderungen an Betrieb, Management und Wartung der Anwendung
//* zu beachtende Standards, Normen und Regeln
* *ZAO-1 Standards:*
** Die Software muss dem Wertekanon des StuRa entsprechen
** Die Datensicherung muss ausschließlich lokal erfolgen

=== Rechtliche Anforderungen
//Angaben ergänzen, nicht relevante Unterpunkte streichen oder auskommentieren
* *ZAR-1 Lizensierung:* +
Die Anwendung soll Open-Source sein

* *ZAR-2 Datenschutz:* +
Das System muss den Datenschutzanforderungen der HTW Dresden, des StuRas und der DSGVO entsprechen
