= Vision: {I6 - Mitgliederdatenbank für StuRa}
Vorname Nachname <email@domain.org>; Vorname2 Nachname2 <email2@domain.org>; Vorname3 Nachname3 <email3@domain.org>
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]
// Platzhalter für weitere Dokumenten-Attribute


== Einführung
Der Zweck dieses Dokuments ist es, die wesentlichen Bedarfe und Funktionalitäten des Projektes: I6 - Mitgliederdatenbank für StuRa zu sammeln, zu analysieren und zu definieren. Der Fokus liegt auf den Fähigkeiten, die von Stakeholdern und adressierten Nutzern benötigt werden, und der Begründung dieser Bedarfe. Die Details, wie das Projekt diese Bedarfe erfüllt, werden in dem Use-Case Model und den System-Wide Requirements beschrieben.

Stakeholder:

* Kunde: StuRa der HTW Dresden
* Ansprechpartnerin: Elisa Range

=== Zweck
Der Zweck dieses Dokuments ist es, die wesentlichen Anforderungen an das System aus Sicht und mit den Begriffen der künftigen Anwender zu beschreiben.

=== Gültigkeitsbereich (Scope)
Dieses Visions-Dokument bezieht sich auf die Mitgliederdatenbank des StuRa der HTW Dresden, das vom Team I6 entwickelt wird. Das System wird es dem StuRa erlauben, eine Mitgliederdatenbank zu nutzen, um damit ein hauseigenes System zu besitzen, welches ihnen ermöglicht, sämtliche Mitglieder des StuRa zu verwalten. 

=== Definitionen, Akronyme und Abkürzungen
//Verweis passend zum Belegabgabe-Template se1_belegabgabe_t00.adoc
Siehe <<#glossary, Glossar>>.

=== Referenzen
(hier externe Verweise zu anderen Dokumenten, Quellen, Standards etc. einfügen, sofern notwendig)


== Positionierung

=== Fachliche Motivation
Der Studierendenrat der Htw Dresden beschäftigt sich mit den Wünschen, Problemen und Anforderungen der Studierenden der HTW. Er arbeitet eng mit der Hochschulleitung und des Studentenwerkes des Landes Sachsen zusammen um die Studienbedinungen zu verbessern. Hierfür fallen zahlreiche Arbeiten an, welche durch eine entsprechende Anzahl von Mitgliedern im StuRa bearbeitet werden müssen. Zur Zeit sind 205 Mitglieder (Stand 19.12.2022) im StuRa tätig. Hierfür existiert eine Excel-Tabelle, die die Mitglieder listet und zusätzlich Informationen über ihre Position im StuRa beinhaltet. Bei dieser Zahl an Angehörigen verliert man schnell den Überblick und eine ordentliche Organisation ist nahezu unmöglich.
Dieses Projekt beschäftigt sich mit den angesprochenen Problemen. Hierfür soll ein hauseigenes System entwickelt werden, welches es ermöglicht alle Mitglieder übersichtlich zu listen und zu bearbeiten, neue Mitglieder einfach anzulegen und ausgeschiedene zu entfernen. Außerdem sollen Arbeitsaufgaben im System verteilt werden können.

=== Problem Statement
//Stellen Sie zusammenfassend das Problem dar, das mit diesem Projekt gelöst werden soll. Das folgende Format kann dazu verwendet werden:

[cols="1,3"]
|===
| Das Problem | Unübersichtliche und unpraktische Organisation der Mitglieder im StuRa
| betrifft | den StuRa
| die Auswirkung davon ist | Unübersichtlichkeit; Fehleranfälligkeit; unzureichende Bearbeitungsmöglichkeit
| eine erfolgreiche Lösung wäre | ein System, welches Mitglieder übersichtlich listet und Bearbeitung zulässt, einfach hinzufügen und löschen lässt und ggf. zusätzliche Anwendungen
|===

////
Beispiel:
[cols="1,3"]
|===
|Das Problem | aktuelle Informationen zum Stundenplan und Noten einfach zu erhalten
|betrifft | Studierende der HTW Dresden
|die Auswirkung davon ist | umständliche und aufwändige Suche nach Noten, Zeiten und Räumen
|eine erfolgreiche Lösung wäre | die Zusammenführung und benutzer-individuelle Darstellung auf einem mobilen Endgerät
|===
////

=== Positionierung des Produkts
//Ein Positionierung des Produkts beschreibt das Einsatzziel der Anwendung und die Bedeutung das Projekts an alle beteiligten Mitarbeiter.

//Geben Sie in knapper Form übersichtsartig die Positionierung der angestrebten Lösung im Vergleich zu verfügbaren Alternativen dar. Das folgende Format kann dazu verwendet werden:

[cols="1,3"]
|===
| Für | Mitglieder des StuRa
| die | Pflege der Mitglieder zulässt
| Das Produkt / die Lösung ist ein | Programm?
| die | die Daten für alle Mitglieder organisiert
| Im Gegensatz zu | zu Excel Tabellen
| Unser Produkt | ermöglicht die übersichtliche Organisation der Mitglieder des StuRa
|===

////
Beispiel Produkt:
|===
| Für | Studierende der HTW
| die | die ihren Studienalltag effizienter organisieren möchten
| Das Produkt ist eine | mobile App für Smartphones
| Die | für den Nutzer Informationen zum Stundenplan und Noten darstellt
| Im Gegensatz zu | Stundenplänen der Website und HIS-Noteneinsicht
| Unser Produkt | zeigt nur die für den Nutzer relevanten Informationen komfortabel auf dem Smartphone an.
|===
////


== Stakeholder Beschreibungen

=== Zusammenfassung der Stakeholder

[%header, cols="1,3,3"]
|===
| Name | Beschreibung | Verantwortlichkeiten

| HTW Dresden | Hochschule | stellt Studierende für StuRa, zahlt AE an die jeweiligen Studierenden
| Mitglieder StuRa | Vertreter der Studierenden der HTW | Nutzer des Produkts
| Systembetreuer, Admin | Systemadministrator | Für die Funktionalität, Wartung und Aktualisierung des Produkts verantwortlich
| Hacker | Personen, die das System von außen stören können | Gefahr, da sensible Daten ausgetauscht werden
|===

=== Benutzerumgebung

//Zutreffendes angeben, nicht zutreffendes streichen oder auskommentieren
. Anzahl der Personen, die an der Erfüllung der Aufgabe beteiligt sind ändert sich vorerst nicht.
. Die Bearbeitungszeit soll schnell gehen. Hierfür werden je nach Datenumfang 2-10 Minuten geschätzt
. Das Produkt soll an jedem Computer verwendbar und intuitiv bedienbar sein.
. Als Systemplattformen werden Windows und Linux eingesetzt.
. Es soll eine Benutzung von Antragsgrün über das Pordukt möglich sein.


== Produkt-/Lösungsüberblick

=== Bedarfe und Hauptfunktionen
//Vermeiden Sie Angaben zum Entwurf. Nennen wesentliche Features (Produktmerkmale) auf allgemeiner Ebene. Fokussieren Sie sich auf die benötigten Fähigkeiten des Systems und warum (nicht wie!) diese realisiert werden sollen. Geben Sie die von den Stakeholdern vorgegebenen Prioritäten und das geplante Release für die Veröffentlichung der Features an.

[%header, cols="4,1,4,1"]
|===
| Bedarf | Priorität | Features | Geplantes Release
| xx | xx | xx | xx
|===


== Zusätzliche Produktanforderungen
//Zutreffendes angeben, nicht zutreffendes streichen oder auskommentieren
Hinweise:

. Führen Sie die wesentlichen anzuwendenden Standards, Hardware oder andere Plattformanforderungen, Leistungsanforderungen und Umgebungsanforderungen auf
. Definieren Sie grob die Qualitätsanforderungen für Leistung, Robustheit, Ausfalltoleranz, Benutzbarkeit und ähnliche Merkmale, die nicht von den genannten Features erfasst werden.
. Notieren Sie alle Entwurfseinschränkungen, externe Einschränkungen, Annahmen oder andere Abhängigkeiten, die wenn Sie geändert werden, das Visions-Dokument beeinflussen. Ein Beispiel wäre die Annahme, dass ein bestimmtes Betriebssystem für die vom System erforderliche Hardware verfügbar ist. Ist das Betriebssystem nicht verfügbar, muss das Visions-Dokument angepasst werden.
. Definieren Sie alle Dokumentationsanforderugen, inkl. Benutzerhandbücher, Onlinehilfe, Installations-, Kennzeichnungs- und Auslieferungsanforderungen-
. Definieren Sie die Priorität für diese zusätzlichen Produktanforderungen. Ergänzen Sie, falls sinnvoll, Angaben zu Stabilität, Nutzen, Aufwand und Risiko für diese Anforderungen.

[%header, cols="4,1,1"]
|===
| Anforderung | Priorität | Geplantes Release
| xx | xx | xx
|===
