= Projektplan: {project-name}

//Vorname Nachname <email@domain.org>; Vorname2 Nachname2 <email2@domain.org>; Vorname3 Nachname3 <email3@domain.org>
//{localdatetime}
include::../_includes/default-attributes.inc.adoc[]
// Platzhalter für weitere Dokumenten-Attribute


== Einführung
//Briefly describe the content of the project plan.

In diesem Projektplan werden die Organisation, Praktiken, und Meilensteine des Teams beschrieben. Dieser Plan wird im Laufe des Projekts vervollständigt und angepasst und dient als Grundlage um die Kommunikation zwischen dem Team und dem Auftraggeber zu erleichtern und die Projektziele vor Augen zu haben.

== Projektorganisation
//Introduce the project team, team members, and roles that they play during this project. If applicable, introduce work areas, domains, or technical work packages that are assigned to team members. Introduce neighboring projects, relationships, and communication channels. If the project is introduced somewhere else, reference that location with a link.

Die Projektarbeit gliedert sich in verschiedene Inhaltsbereiche. Jeder Bereich wird von einem Mitglied geleitet und kann weitere Mitwirkende haben, was in der folgenden Rollenübersicht dargestellt wird. Der jeweilige Leiter ist verantwortlich, dass Bugs und Verbesserungswünsche gesichtet und zugewiesen werden.


Projekt Management: +
Tony Heinz Hörnig (SE1)
Georg Schicker (SE2)

Analyst: +
Nathalie Kästner +
Dang Tam Hao Nguyen (SE1)

Architekt: +
Lennart Bronke

Entwickler: +
Collin Neumann +
Paul Wentzel

Tester: +
Georg Schicker
Paul Wentzel

== Praktiken und Bewertung
//Describe or reference which management and technical practices will be used in the project, such as iterative development, continuous integration, independent testing and list any changes or particular configuration to the project. Specify how you will track progress in each practice. As an example, for iterative development the team may decide to use iteration assessments and iteration burndown reports and collect metrics such as velocity (completed work item points/ iteration).

Der im Rahmen der  Lehrveranstaltung vorgestellte Open Unified Process wird als technische Praktik genutzt. Es wird agil gearbeitet. In jeder Iteration (14-tägig) wird ein Teil des Lösungsprozesses umgesetzt, dadurch wird das Risiko auf eine falsche Lösung vermindert. Es findet vor jeder Iteration ein Meeting statt um Aufgaben, Aufwand, Risiken zu Besprechen und mit dem Projektgeber zu kommunizieren um einen reibungslosen Ablauf zu ermöglichen. Die Planung wird in einem Protokoll und auf Github festgehalten.

== Meilensteine und Ziele
//Define and describe the high-level objectives for the iterations and define milestones. For example, use the following table to lay out the schedule. If needed you may group the iterations into phases and use a separate table for each phase

[%header, cols="1,3a,2"]
|===
| Iteration
| Primary objectives +
(risks and use case scenarios)
| Scheduled start or milestone


| I1
|
* Team organisieren (Aufgabe kennenlernen, Rollenverteilung)
* Kontakt zum StuRa und Coach aufnehmen
* link:iteration_plan_01.adoc[Iterationsplan 01]
| 30.11.2022-20.12.2022


| I2
|
* link:iteration_plan_02.adoc[Iterationsplan 02]
| 21.12.2022-13.01.2023


| I3
|
* link:iteration_plan_03.adoc[Iterationsplan 03]
| 14.01.2023-27.01.2023
|===

=== Ziele
  1. Kurzfristig:
	- Wöchentliche Meetings im Team und regelmäßige Absprachen mit dem Auftraggeber
		- Aufgaben werden in iterativen Zyklen vergeben und abgearbeitet
2. Langfristig
	- Entwicklung einer funktionalen Software, für den Prozess der Mitgliederverwaltung des StuRa


== Deployment
//Outline the strategy for deploying the software (and its updates) into the production environment.

Das System wird auf dem Server des StuRa laufen. Die Software wird nach Fertigstellung an ausgewählte verantwortliche Personen weitergegeben um diese zu in ihr System zu integrieren. Der Einrichtungsprozess und Bedienung der Software wird vor der Übergabe geklärt, damit eine reibungslose Umstellung und nachfolgender Einsatz der Software möglich ist.

== Erkenntnisse (Lessons learned)
//List lessons learned from the retrospective, with special emphasis on actions to be taken to improve, for example: the development environment, the process, or team collaboration.

-	Kommunikation in regelmäßigen Abständen mit den Stakeholdern und im Team ist sehr wichtig
-	Iterative Planung ist wichtig, um gut voranzukommen 
-	Zuverlässigkeit der Teammitglieder ist wichtig um ein gutes/produktives Teamklima zu schaffen
