# Generated by Django 3.1.5 on 2021-05-08 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aemter', '0001_initial'),
        ('kandidaturen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kandidatur',
            name='email',
        ),
        migrations.RemoveField(
            model_name='kandidatur',
            name='funktion',
        ),
        migrations.AddField(
            model_name='kandidatur',
            name='spitzname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='KandidaturMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('kandidatur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kandidaturen.kandidatur')),
            ],
            options={
                'verbose_name': 'Zuordnung Kandidatur-Mail',
                'verbose_name_plural': 'Zuordnungen Kandidatur-Mail',
            },
        ),
        migrations.CreateModel(
            name='KandidaturAmt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funktion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aemter.funktion')),
                ('kandidatur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kandidaturen.kandidatur')),
            ],
            options={
                'verbose_name': 'Zuordnung Kandidatur-Amt',
                'verbose_name_plural': 'Zuordnungen Kandidatur-Amt',
            },
        ),
        migrations.CreateModel(
            name='HistoricalKandidaturMail',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('kandidatur', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='kandidaturen.kandidatur')),
            ],
            options={
                'verbose_name': 'historical Zuordnung Kandidatur-Mail',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalKandidaturAmt',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('funktion', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='aemter.funktion')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('kandidatur', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='kandidaturen.kandidatur')),
            ],
            options={
                'verbose_name': 'historical Zuordnung Kandidatur-Amt',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalKandidatur',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('vorname', models.CharField(max_length=50)),
                ('spitzname', models.CharField(max_length=50, null=True)),
                ('wahldatum', models.DateField(null=True)),
                ('beschlussnummer', models.CharField(max_length=50, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Kandidatur',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
