# Generated by Django 3.1.5 on 2021-05-08 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kandidaturen', '0002_auto_20210509_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalkandidaturamt',
            name='amtszeit_beginn',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='historicalkandidaturamt',
            name='amtszeit_ende',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='kandidaturamt',
            name='amtszeit_beginn',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='kandidaturamt',
            name='amtszeit_ende',
            field=models.DateField(null=True),
        ),
    ]
