# Generated by Django 3.1.5 on 2021-05-26 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kandidaturen', '0003_auto_20210509_0155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalkandidaturamt',
            name='amtszeit_beginn',
        ),
        migrations.RemoveField(
            model_name='historicalkandidaturamt',
            name='amtszeit_ende',
        ),
        migrations.RemoveField(
            model_name='kandidaturamt',
            name='amtszeit_beginn',
        ),
        migrations.RemoveField(
            model_name='kandidaturamt',
            name='amtszeit_ende',
        ),
    ]
