# Generated by Django 4.2.2 on 2023-06-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aemter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalfunktion',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Funktion', 'verbose_name_plural': 'historical Funktionen'},
        ),
        migrations.AlterModelOptions(
            name='historicalfunktionrecht',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Zuordnung Funktion-Recht', 'verbose_name_plural': 'historical Zuordnungen Funktion-Recht'},
        ),
        migrations.AlterModelOptions(
            name='historicalorganisationseinheit',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Organisationseinheit', 'verbose_name_plural': 'historical Organisationseinheiten'},
        ),
        migrations.AlterModelOptions(
            name='historicalrecht',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Recht', 'verbose_name_plural': 'historical Rechte'},
        ),
        migrations.AlterModelOptions(
            name='historicalunterbereich',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Unterbereich', 'verbose_name_plural': 'historical Unterbereiche'},
        ),
        migrations.AlterField(
            model_name='historicalfunktion',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalfunktionrecht',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalorganisationseinheit',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalrecht',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalunterbereich',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
